# The URL the site will be built for
base_url = "https://chris0030.github.io"
theme = "lunar-zen"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "Chris Weaver"
description = "Chris Weaver's blog site."

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
author = "Chris Weaver"
github = "github author name"
twitter = "twitter author name"
icon_alt = "avatar image of a crescent moon"
license = "<a rel=\"license\" href=\"http://creativecommons.org/licenses/by-nc-sa/4.0/\"><img alt=\"Creative Commons License CC BY-NC-SA\" style=\"vertical-align:middle;border-width:0\" width=80 height=15 src=\"/by-nc-sa-80x15.png\" /></a>"